#!/usr/bin/env python3

import os
import sys
import subprocess


def system(*args, **kwargs):
    kwargs.setdefault("stdout", subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return out, err


def main():
    output, err = system(
        "python3", os.path.join("cidc_ngs_pipeline_api", "wes", "wes_output_API.py")
    )
    if output:
        print(output)
    if err:
        os.exit(err)

    output, err = system(
        "git",
        "add",
        os.path.join("cidc_ngs_pipeline_api", "wes", "wes_output_API.json"),
    )
    if output:
        print(output)
    if err:
        os.exit(err)

    output, err = system(
        "git",
        "add",
        os.path.join("cidc_ngs_pipeline_api", "wes", "wes_output_API.json"),
    )
    if output:
        print(output)
    if err:
        os.exit(err)


main()
